---
- name: Add unit file for application
  template:
    src: app.service.j2
    dest: /etc/systemd/system/app.service
  notify: restart app

- name: enable app
  systemd: 
    name: app
    enabled: yes