---
- name: Install the gpg key for NodeJS LTS
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install the NodeJS LTS repos
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_13.x xenial main"
    state: present
    update_cache: yes

- name: Install NodeJS package
  apt:
    name: nodejs
    state: present